carl9170 firmware: add missing out-of-bound check in WoWLAN code
src/wlan.c: In function ‘wlan_rx_wol_probe_ssid’:
src/wlan.c:830:30: error: variable ‘end’ set but not used

Signed-off-by: Christian Lamparter <chunkeey@googlemail.com>