carl9170 firmware: fix off-by-one error when CARL9170FW_USB_MODESWITCH is set
usb/usb.c: In function ‘usb_set_configuration’:
usb/usb.c:544:1: error: control reaches end of non-void function [-Werror=return-type]

Signed-off-by: Christian Lamparter <chunkeey@googlemail.com>