shared: fix build errors due to -Wno-error=unterminated-string-initialization in -Wextras in gcc 15
| In file included from carlfw/include/fwdsc.h:28,
|                 from carlfw/src/fw.c:22:
| carlfw/../include/shared/fwdesc.h:82:25: error: initializer-string for array of
| ‘unsigned char’ truncates NUL terminator but destination lacks ‘nonstring’ attribute
| (5 chars into 4 available)
|   82 | #define OTUS_MAGIC      "OTAR"
|      |                         ^~~~~~
| carlfw/../include/shared/fwdesc.h:215:26: note: in definition of macro ‘CARL9170FW_FILL_DESC’
|  215 |                 .magic = _magic,                                        \
|      |                          ^~~~~~
|carlfw/src/fw.c:26:38: note: in expansion of macro ‘OTUS_MAGIC’
|   26 |                 CARL9170FW_FILL_DESC(big##_MAGIC,                       \
|      |                                      ^~~
|carlfw/src/fw.c:34:9: note: in expansion of macro ‘FILL’
|   34 |         FILL(otus, OTUS,
|      |         ^~~~

Signed-off-by: Christian Lamparter <chunkeey@gmail.com>