carl9170 firmware: USB_MODESWITCH depends on USB_STANDARD_CMDS
usb.c:170:13: error: ‘usb_reset_eps’ defined but not used

Signed-off-by: Christian Lamparter <chunkeey@googlemail.com>